from __future__ import annotations

import subprocess
from pathlib import Path


class CommandRunnerError(RuntimeError):
    pass


def run_shell_command(command: str, cwd: Path | None = None) -> str:
    """Run a shell command and return combined stdout/stderr.

    This is intentionally simple for the first musubi-tuner GUI version.
    A later version can stream logs line-by-line into Gradio.
    """
    if not command.strip():
        raise CommandRunnerError("Empty command")

    proc = subprocess.run(
        command,
        shell=True,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    output = proc.stdout or ""
    if proc.returncode != 0:
        raise CommandRunnerError(f"Command failed with exit code {proc.returncode}\n\n{output}")
    return output


def split_command_sections(command_preview: str) -> dict[str, str]:
    """Split command preview into latent/text/train command sections.

    Expected markers are generated by app/commands.py.
    """
    sections: dict[str, str] = {}
    current_name: str | None = None
    current_lines: list[str] = []

    def flush() -> None:
        nonlocal current_name, current_lines
        if current_name and current_lines:
            sections[current_name] = "\n".join(line for line in current_lines if line.strip() and not line.strip().startswith("#"))
        current_lines = []

    for line in command_preview.splitlines():
        stripped = line.strip()
        if stripped.startswith("# 1. Latent cache"):
            flush()
            current_name = "latent_cache"
            continue
        if stripped.startswith("# 2. Text encoder cache"):
            flush()
            current_name = "text_cache"
            continue
        if stripped.startswith("# 3. Train LoRA"):
            flush()
            current_name = "train"
            continue
        if current_name:
            current_lines.append(line)
    flush()
    return sections


def run_preview_section(command_preview: str, section: str, cwd: Path | None = None) -> str:
    sections = split_command_sections(command_preview)
    command = sections.get(section, "").strip()
    if not command:
        return f"NG: command section not found: {section}"
    return run_shell_command(command, cwd=cwd)
